#+TITLE: Bayes Nash equilibrium
#+AUTHOR:    Christoph Schottmüller
#+DATE:       
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:2 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport

#+startup: beamer
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [bigger]
#+BEAMER_FRAME_LEVEL: 2
#+latex_header: \mode<beamer>{\useinnertheme{rounded}\usecolortheme{rose}\usecolortheme{dolphin}\setbeamertemplate{navigation symbols}{}\setbeamertemplate{footline}[frame number]{}}
#+latex_header: \mode<beamer>{\usepackage{amsmath}\usepackage{ae,aecompl,sgamevar,tikz}}
#+LATEX_HEADER:\let\oldframe\frame\renewcommand\frame[1][allowframebreaks]{\oldframe[#1]}
#+LATEX_HEADER: \setbeamertemplate{frametitle continuation}[from second]
#+LATEX_HEADER: \newcommand{\Ra}{\Rightarrow} \newcommand{\ra}{\rightarrow} \newcommand{\Lra}{\Leftrightarrow}

** Introduction
- so far
  - need to look at games of incomplete information (preference aggregation when preferences are private, auctions)
  - under certain assumptions decision makers can be modeled as expected utility maximizers
- still missing
  - how to react to information?
  - strategic interaction under uncertainty


* Bayes' rule
** Bayes' rule: A simple example
   - I know someone who lives in Munich. What is the probability that this person is male?
   - I know someone who lives in Munich and who is 1.90 m tall. What is the probability that this person is male?
   - I know someone who lives in Munich and has green eyes. What is the probability that this person is male?
# about 1/2, definitely higher than 1/2 as there are more men than women with this height, about 1/2 as the fraction of mean and women with green eyes is about the same
# eye color does not give more information on gender while height does; in statistics eye color and gender would be called independent while height and gender a correlated
** Bayes' rule
*** Bayes' rule
   For two events $A$ and $B$
   $$P(A|B)=\frac{P(B|A) P(A)}{P(B)}.$$
   
*** :B_ignoreheading:BMCOL:
    :PROPERTIES:
    :BEAMER_env: ignoreheading
    :BEAMER_col: 0.4
    :END:
- easier to remember as $P(A|B)P(B)=P(B|A)P(A)$ which is also equal to $P(A\cap B)$
- hence, $P(A|B)=P(A\cap B)/P(B)$  

#+BEGIN_SRC latex   
  \begin{figure}   
  \begin{tikzpicture}[scale=0.7]
  \draw[thick] (0,0) rectangle (3,3) ;
  \draw [blue] (1,1.2) circle [radius=0.9];
  \draw[red] (1,1.2) rectangle (2.5,2.5) ;
   \node[right,red] at (2.4,2.5) {$A$};
  \node[right,blue] at (1.6,0.6) {$B$};
  \node at (1.42,1.45) {\tiny$A\cap B$}; 
  \end{tikzpicture}
  \end{figure}
#+End_SRC

** Bayes' rule: example
   - an antigen test for a certain virus is 70% reliable at detecting an illness and 99.5% reliable at correctly reporting that somebody is healthy
   - suppose about 80.000 people are currently infected with the virus
   - suppose 80 million people live in Germany
   - if a random person takes the test and the test is positive, what is the probability that this person is infected?
     # P(infect)= 80.000/80mil = 0.001 , P(pos test| infect)=0.7, P(pos test)=0.001*0.7+0.999*0.005=
     # P(infect|pos test) = 0.7*0.001/(0.005695)=0.1229 i.e. 12 %
** Bayes' rule: comments
   - calculations are reasonably simple
   - intuition often goes wrong when the prior is extremely skewed
   - make sure to understand it as it will often loom in the background
** Independence
*** Independence
    Two random variables $X$ and $Y$ are independent if
     $$P(X=x,Y=y)=P(X=x)P(Y=y).$$

*** :B_ignoreheading:BMCOL:
    :PROPERTIES:
    :BEAMER_env: ignoreheading
    :BEAMER_col: 0.4
    :END:

   - by Bayes' rule, $P(X=x|Y=y)=P(X=x)$ if $X$ and $Y$ are independent
     - knowing $Y$ does not affect my belief about $X$ 

   - independence will often be assumed to keep the models simple   
* Games of incomplete information
** Games of incomplete information I: an example
- two firms simultaneously decide whether to enter (E) a new market or not (N)

  
#+Caption: Payoffs 
|    | E             | N  |
|----+---------------+-----|
| /  | <             |     |
| E | $t_1-3,t_2-3$ | $t_1,0$ |
| N | $0,t_2$    | 0,0 |

- $t_i$ is the quality of firm $i$'s product which is either 2 or 4
- each firm knows its own quality but not the quality of its competitor  
- how to solve this game?

** Games of incomplete information IV: belief/nature
   - add a belief to the game description:
     - with which probability does firm $i$ believe the quality of $j$ is low/high?
     - e.g. $p(2)=p(4)=1/2$ (independent of $i$'s quality)
     - we assume that $i$ knows or anticipates $j$'s belief
   - alternative story:
     - a player called /nature/ chooses in a first step the quality of both firms
     - e.g. nature chooses $2$ and $4$ both with probability $1/2$
     - the incumbent observes the costs chosen by nature and the entrant does not
     - afterwards players play the game
     - as this game description is common knowledge, each firm $i$ views both $2$ and $4$ as equally likely for $t_j$ and knows that the other firm does so as well
   - maximize expected utility (use belief to construct expectation)

** Games of incomplete information V: strategy
   - a strategy of a player is a /complete plan of action/
     - a pure strategy of firm $i$ consists of one action in case it has quality of 2 and one action in case it has quality 4!
     - nature interpretation: a strategy tells you how to act at every point in the game tree!

       
** Games of incomplete information VI:  back to example
   - assume that each player believes that the other player has $t_i=2$ with probability $1/2$ and $t_i=4$ with probability $1/2$ (independent of own type) 

#+Caption: Payoffs 
|    | E             | N  |
|----+---------------+-----|
| /  | <             |     |
| I  | $t_1-3,t_2-3$ | t_1,0 |
| N | $0,t_2$    | 0,0 |

- what is a firm's optimal strategy if  $t_i=4$?
- if the firm $j$ plays E with probability $s_j$ in case $t_j=2$, what is $i$'s best response if $t_i=2$?
- what are the equilibria in this game?

# t_i=4 has dominant action to enter, for t_i=2 u_i^E=1/2 * (2-3) +1/2 * (s_j*(-1)+(1-s_j)*2) while u_i^N=0, hence b.r. is enter iff s_j\leq 1/3.
# BNE: asymmetric and pure: one firm enters with both types and the other only if t_i=4; symmetric and mixed: both firms enter if $t_i=4 and enter with probability 1/3 if t_i=2
   
** Games of incomplete information VII: description
   A (static) game of incomplete information consists of
   - set of players
   - action set for each player ($S_i$)
   - a "type set" for each player ($T_i$)
   - a probability distribution $p$ over types from which nature draws
   - a utility function $u_i$ for each player that depends on chosen strategies and types

** pure strategy Bayesian Nash equilibrium
   - a pure strategy for each player $s_i: T_i\rightarrow A_i$
     - recall: a pure strategy assigns to each type of a player one action
   - the action of each type of player $i$ maximizes expected utility of player $i$ given the strategies of all the other players 


* Public good example

** public good example I
   - $N$ guests at a garden party
   - each guest has to decide whether to bring a speaker to play music, $S_i=\{0,1\}$
   - payoff of player $i$:
     - zero if no one brings a speaker
     - $t_i$ if someone else brought a speaker
     - $t_i-1/2$ if person $i$ brought a speaker
   - $t_i$ are independently distributed and $1$ (high) with probability $2/3$ and $0$ (low) with probability $1/3$
   - we want to find a /symmetric BNE/, i.e. one where all high types use one strategy and all low types use one other strategy

** public good example II
   - what is the optimal strategy of a low type?
     # do not bring speaker
   - suppose all high types bring a speaker with probability $\alpha$
     - for player $i$: what is the probability that no one else brings a speaker?
     # prob that j brings speaker is 2\alpha/3 -> (1-2\alpha/3)^(N-1)
     - what is the expected payoff for a high type of player $i$ when bringing the speaker?
     # 1-1/2=1/2
     - what is the expected payoff for a high type of player $i$ when not bringing the speaker?
     # 1-(1-2\alpha/3)^(N-1)
   - which value of $\alpha$ gives a BNE?
     # 1/2=1-(1-2\alpha/3)^(N-1), i.e. (1/2)^(1/(N-1))=1-2\alpha/3 or \alpha = 3/2[1-(1/2)^(1/(N-1))]
     \vspace*{0.5cm}
#+BEGIN_SRC latex   
      \begin{figure}   
      \begin{tikzpicture}
      \draw[<->,thick] (1,1) -- (1,0) -- (10,0);
      \draw[thick,domain=2:10, blue] plot (\x,{1.5*(1-(0.5)^(1/(\x-1)))});
      \node[left] at (1,1.1) {$\alpha$};
      \node[right] at (10,0) {$N$};
      \node[below] at (5,0){5};
      \node[below] at (2,0){2};
    \node[below] at (10,0){10};
    \node[left] at (1,0.5){\tiny 1/2};
     \draw (0.95,0.5)--(1.05,0.5);
     \draw (0.95,0.75)--(1.05,0.75);
  \node[left] at (1,0.75){\tiny 3/4};
      \end{tikzpicture}
      \end{figure}
#+End_SRC

