#+TITLE: Bayes Nash equilibrium
#+AUTHOR:    Christoph Schottmüller
#+DATE:       
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:2 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport

#+startup: beamer
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [bigger]
#+BEAMER_FRAME_LEVEL: 2
#+latex_header: \mode<beamer>{\useinnertheme{rounded}\usecolortheme{rose}\usecolortheme{dolphin}\setbeamertemplate{navigation symbols}{}\setbeamertemplate{footline}[frame number]{}}
#+latex_header: \mode<beamer>{\usepackage{amsmath}\usepackage{ae,aecompl,tikz,istgame,sgamex}}
#+LATEX_HEADER:\let\oldframe\frame\renewcommand\frame[1][allowframebreaks]{\oldframe[#1]}
#+LATEX_HEADER: \setbeamertemplate{frametitle continuation}[from second]
#+LATEX_HEADER: \newcommand{\Ra}{\Rightarrow} \newcommand{\ra}{\rightarrow} \newcommand{\Lra}{\Leftrightarrow}

** Introduction
- so far
  - need to look at games of incomplete information (preference aggregation when preferences are private, auctions)
  - under certain assumptions decision makers can be modeled as expected utility maximizers
- still missing
  - how to react to information?
  - strategic interaction under uncertainty


* Bayes' rule
** Bayes' rule: A simple example
   - I know someone who lives in Munich. What is the probability that this person is male?
   - I know someone who lives in Munich and who is 1.90 m tall. What is the probability that this person is male?
   - I know someone who lives in Munich and has green eyes. What is the probability that this person is male?
# about 1/2, definitely higher than 1/2 as there are more men than women with this height, about 1/2 as the fraction of mean and women with green eyes is about the same
# eye color does not give more information on gender while height does; in statistics eye color and gender would be called independent while height and gender a correlated
** Bayes' rule
*** Bayes' rule
   For two events $A$ and $B$
   $$P(A|B)=\frac{P(B|A) P(A)}{P(B)}.$$
   
*** :B_ignoreheading:BMCOL:
    :PROPERTIES:
    :BEAMER_env: ignoreheading
    :BEAMER_col: 0.4
    :END:
- easier to remember as $P(A|B)P(B)=P(B|A)P(A)$ which is also equal to $P(A\cap B)$
- hence, $P(A|B)=P(A\cap B)/P(B)$  

#+BEGIN_SRC latex   
  \begin{figure}   
  \begin{tikzpicture}[scale=0.7]
  \draw[thick] (0,0) rectangle (3,3) ;
  \draw [blue] (1,1.2) circle [radius=0.9];
  \draw[red] (1,1.2) rectangle (2.5,2.5) ;
   \node[right,red] at (2.4,2.5) {$A$};
  \node[right,blue] at (1.6,0.6) {$B$};
  \node at (1.42,1.45) {\tiny$A\cap B$}; 
  \end{tikzpicture}
  \end{figure}
#+End_SRC

** Bayes' rule: example
   - an antigen test for a certain virus is 70% reliable at detecting an illness and 99.5% reliable at correctly reporting that somebody is healthy
   - suppose about 80.000 people are currently infected with the virus
   - suppose 80 million people live in Germany
   - if a random person takes the test and the test is positive, what is the probability that this person is infected?
     # P(infect)= 80.000/80mil = 0.001 , P(pos test| infect)=0.7, P(pos test)=0.001*0.7+0.999*0.005=
     # P(infect|pos test) = 0.7*0.001/(0.005695)=0.1229 i.e. 12 %
** Bayes' rule: comments
   - calculations are reasonably simple
   - intuition often goes wrong when the prior is extremely skewed
   - make sure to understand it as it will often loom in the background
** Independence
*** Independence
    Two random variables $X$ and $Y$ are independent if
     $$P(X=x,Y=y)=P(X=x)P(Y=y).$$

*** :B_ignoreheading:BMCOL:
    :PROPERTIES:
    :BEAMER_env: ignoreheading
    :BEAMER_col: 0.4
    :END:

   - by Bayes' rule, $P(X=x|Y=y)=P(X=x)$ if $X$ and $Y$ are independent
     - knowing $Y$ does not affect my belief about $X$ 

   - independence will often be assumed to keep the models simple   
* Games of incomplete information
** Games of incomplete information I: an example
- Fleur invited Emir for dinner
- Emir has to decide whether to bring /wine/ or /beer/
  - payoff of 1 if he brings Fleur's favorite drink (0 otherwise)
- Fleur has to decide whether to buy her favorite drink or not
  - payoff of 2 from her favorite drink but cost of 1 from shopping
- Emir does not know Fleur's favorite drink
  \pause
- payoffs are not commonly known
- what is Emir's belief about Fleur's preferences?
- what does Fleur believe about Emir's beliefs about her preferences?
- complicated: we need a trick!
  
** Games of incomplete information II: Harsanyi's trick
- add an artificial player /nature/ acting first
- nature chooses Fleur's favorite drink according to a fixed probability distribution and has no payoffs
- Fleur observes nature's choice, Emir does not
  - nature's probability distribution can be interpreted as Emir's belief
- transforms game of incomplete information (unknown payoffs) into a game of imperfect information (prior choice of nature unknown)

** Games of incomplete information III
\begin{figure}[h]
  \centering
  \begin{istgame}
%nature     
\xtdistance{15mm}{60mm}
\istroot(0){nature}
\istb{$2/3$}[left]
\istb{$1/3$}[right]
\endist
%Emir
\xtdistance{15mm}{30mm}
\istroot(1)(0-1)
\istb{wine}[l]
\istb{beer}[r]
\endist
\istroot(2)(0-2)
\istb{wine}[l]
\istb{beer}[r]
\endist
\xtInfoset(1)(2){Emir}
%Fleur left
\xtdistance{15mm}{15mm}
\istroot(3)(1-1)
\istb{shop}[l]{(1,1)}
\istb{not}[r]{(1,2)}
\endist
\istroot(4)(1-2)
\istb{shop}[l]{(0,1)}
\istb{not}[r]{(0,0)}
\endist
\xtInfoset(3)(4){Fleur}
%Fleur right
\istroot(5)(2-1)
\istb{shop}[l]{(0,1)}
\istb{not}[r]{(0,0)}
\endist
\istroot(6)(2-2)
\istb{shop}[l]{(1,1)}
\istb{not}[r]{(1,2)}
\endist
\xtInfoset(5)(6){Fleur}
\end{istgame}
  \caption{Nature as a player determining Fleur's type}
  \label{fig:bne_nature1}
\end{figure}


** Games of incomplete information IV:  normal form (first try)
- Fleur's strategy consists of two choices as there are two information sets at which she has to act (!)
- why is this normal form misleading?
  # nature's strategy not properly depicted
  
\begin{figure}[h]
  \centering
      \begin{game}{2}{4}[Emir][Fleur][wine]
        & $ss$ &  $sn$&$ns$&$nn$ \\
      $w$ & $1,1$&$1,1$&$1,2$   &$1,2$  \\
      $b$ & $0,1$& $0,1$ & $0,0$ &$0,0$
    \end{game}
        \begin{game}{2}{4}[Emir][Fleur][beer]
         & $ss$ &  $sn$&$ns$&$nn$ \\
      $w$ & $0,1$&$0,0$ &$0,1$&$0,0$\\
      $b$ & $1,1$& $1,2$ &$1,1$&$1,2$
    \end{game}
\end{figure}

** Games of incomplete information IV: normal form (second try)
- compute expected payoffs for each strategy profile, e.g. /wine/ and /(shop,not)/ leads to expected payoffs
  - Emir: $1*2/3+0*1/3=2/3$
  - Fleur: $1*2/3+0*1/3=2/3$

\begin{figure}[h]
  \centering
      \begin{game}{2}{4}[Emir][Fleur]
        & $ss$ &  $sn$&$ns$&$nn$ \\
      $w$ & $2/3,1$&$2/3,2/3$&$2/3,5/3$ &$2/3,4/3$  \\
      $b$ & $1/3,1$&$1/3,4/3$&$1/3,1/3$ &$1/3,2/3$
    \end{game}
\end{figure}

- a /Bayesian Nash equilibrium/ of the original incomplete information game is a Nash equilibrium in this auxiliary game with imperfect information (and nature as a dummy player)

** Games of incomplete information V: notation

*** Definition
A (simultaneous move)  game of incomplete information consists of
- set of players $I=\{1,\dots,n\}$,
- a strategy set $S_i$ for each player $i\in I$,
- a type set $\Theta_i$ for each player  $i\in I$,
- a distribution over types $F:\Theta_1\times\dots\times\Theta_n\rightarrow \Re$ and
- a payoff function for each player assigning to each combination of strategy and type profile a payoff; i.e. $u_i:S_1\times\dots\times S_N\times\Theta_1\times\dots\times\Theta_n\rightarrow \Re$.

** Games of incomplete information VI: Bayesian Nash equilibrium I
- a BNE of a game with incomplete information $\langle I,(S_i)_{i\in I},(u_i)_{i\in I},(\Theta_i)_{i\in I} ,F  \rangle$ is a Nash equilibrium of the auxiliary game with imperfect information in which
  - nature chooses types according to $F$
  - each player observes his own chosen type but not the types of the other players
  - player $i$'s (pure) strategy assigns an element of $S_i$ to each $\theta_i\in\Theta_i$ 
  - players maximize expected payoff $u_i$ (taking expectations over other players' types)
** Games of incomplete information VI: Bayesian Nash equilibrium II
2 formal definitions (which are equivalent in games with finite type sets)
- a BNE is a strategy profile $(s_1^*,\dots,s_n^*)$ where $s_i^*:\Theta_i\rightarrow S_i$ is such that
  $$s_i^*\in \arg\max_{s_i: \Theta_i\rightarrow S_i} \mathbb{E}_{\theta}\left[u_i(s_1(\theta_1),\dots,s_n(\theta_n),\theta_1,\dots,\theta_n)\right]$$
  for all $i\in I$.

- a BNE is a strategy profile $(s_1^*,\dots,s_n^*)$ where $s_i^*:\Theta_i\rightarrow S_i$ is such that
  $$s_i^*(\theta_i)\in \arg\max_{s_i\in S_i} \mathbb{E}_{\theta_{-i}}\left[u_i(s_1(\theta_1),\dots, s_i, \dots,s_n(\theta_n),\theta_1,\dots,\theta_n)\right]$$
  for all $\theta_i\in\Theta_i$ and $i\in I$.


** Games of incomplete information VII: entry example
- two firms simultaneously decide whether to enter (E) a new market or not (N)

\begin{figure}[h]
  \centering
      \begin{game}{2}{2}[Firm A][Firm B]
        & $E$ &  $N$ \\
      $E$ & $\theta_A-3,\theta_B-3$&$\theta_A,0$ \\
      $N$ & $0,\theta_B$&$0,0$
  \end{game}
\end{figure}  

- $\theta_i$ is the quality of firm $i$'s product which is either 2 or 4
- each firm knows its own quality but not the quality of its competitor  
- each firm believes that the other firm is equally likely to have low or high quality
** Games of incomplete information VIII: entry example
- expected payoff if both firms choose strategy $EE$: $0.5*(4-3)+0.5*(2-3)=0$
- expected payoff if A chooses $EE$ and B chooses $EN$:
  - A: $0.25*(4-3)+0.25*(4)+0.25*(2-3)+0.25*(2)=1.5$
  - B: $0.25*(4-3)+0.25*(0)+0.25*(4-3)+0.25*(0)=0.5$
  
\begin{figure}[h]
  \centering
      \begin{game}{4}{4}[Firm A][Firm B]
        & $EE$ &  $EN$&$NE$&$NN$ \\
      $EE$ & $0,0$&$1.5,0.5$&$1.5,-0.5$ &$3,0$  \\
      $EN$ & $0.5,1.5$&$1.25,1.25$&$1.25,0.25$ &$2,0$ \\
      $NE$ & $-0.5,1.5$&$0.25,1.25$&$0.25,0.25$ &$1,0$ \\
      $NN$ & $0,3$&$0,2$&$0,1$ &$0,0$
    \end{game}
\end{figure}
# EN: enter if high quality, not enter if low quality

# EN strictly dominates NE and NN; asym NE: (EE,EN) and (EN,EE), mixed symmetric NE: 1/3 EE and 2/3 EN

** Games of incomplete information IX: entry example

\begin{figure}[h]
  \centering
      \begin{game}{2}{2}[Firm A][Firm B]
        & $E$ &  $N$ \\
      $E$ & $\theta_A-3,\theta_B-3$&$\theta_A,0$ \\
      $N$ & $0,\theta_B$&$0,0$
  \end{game}
\end{figure}

alternative way of solving: type by type
- what is a firm's optimal strategy if  $\theta_i=4$?
- if the firm $j$ plays E with probability $s_j(2)$ in case $\theta_j=2$, what is $i$'s best response if $\theta_i=2$?
- what are the BNE in this game?

# \theta_i=4 has dominant action to enter, for \theta_i=2 u_i^E=1/2 * (2-3) +1/2 * (s_j*(-1)+(1-s_j)*2) while u_i^N=0, hence b.r. is enter iff s_j\leq 1/3.
# BNE: asymmetric and pure: one firm enters with both types and the other only if \theta_i=4; symmetric and mixed: both firms enter if $\theta_i=4 and enter with probability 1/3 if \theta_i=2
   

* Public good example

** public good example I
   - $N$ guests at a garden party
   - each guest has to decide whether to bring a speaker to play music, $S_i=\{0,1\}$
   - payoff of player $i$:
     - zero if no one brings a speaker
     - $\theta_i$ if someone else brought a speaker
     - $\theta_i-1/2$ if person $i$ brought a speaker
   - $\theta_i$ are independently distributed and $1$ (high) with probability $2/3$ and $0$ (low) with probability $1/3$
   - we want to find a /symmetric BNE/, i.e. one where\linebreak (i) the high types of all players use the same action \linebreak (ii) the low types of all players use the same action

** public good example II
   - what is the optimal strategy of a low type?
     # do not bring speaker
   - suppose all high types bring a speaker with probability $\alpha$
     - for player $i$: what is the probability that no one else brings a speaker?
     # prob that j brings speaker is 2\alpha/3 -> (1-2\alpha/3)^(N-1)
     - what is the expected payoff for a high type of player $i$ when bringing the speaker?
     # 1-1/2=1/2
     - what is the expected payoff for a high type of player $i$ when not bringing the speaker?
     # 1-(1-2\alpha/3)^(N-1)
   - which value of $\alpha$ gives a BNE?
     # 1/2=1-(1-2\alpha/3)^(N-1), i.e. (1/2)^(1/(N-1))=1-2\alpha/3 or \alpha = 3/2[1-(1/2)^(1/(N-1))]
     \vspace*{0.5cm}
#+BEGIN_SRC latex   
      \begin{figure}   
      \begin{tikzpicture}
      \draw[<->,thick] (1,1) -- (1,0) -- (10,0);
      \draw[thick,domain=2:10, blue] plot (\x,{1.5*(1-(0.5)^(1/(\x-1)))});
      \node[left] at (1,1.1) {$\alpha$};
      \node[right] at (10,0) {$N$};
      \node[below] at (5,0){5};
      \node[below] at (2,0){2};
    \node[below] at (10,0){10};
    \node[left] at (1,0.5){\tiny 1/2};
     \draw (0.95,0.5)--(1.05,0.5);
     \draw (0.95,0.75)--(1.05,0.75);
  \node[left] at (1,0.75){\tiny 3/4};
      \end{tikzpicture}
      \end{figure}
#+End_SRC



* (Very) simple poker

** very simple poker I
   - 2 players
   - each player privately observes his card/type which is either high ($\theta_h$) or low ($\theta_l$)
   - probability of high card is $\alpha\in(0,1)$ (independent across players)
   - players simultaneously either /raise/ ($r$) or /fold/ ($f$)
   - payoffs:
     - $(0,0)$ if both fold or both raise and have the same card
     - $1$ for raising and $-1$ for folding player if actions do not coincide
     - $2$ for high type and $-2$ for low type if both raise and cards differ

** very simple poker II
   - what should a high type play?
     \vspace*{1.5cm}
     # raise is dominant: if other player folds, raise is better; if other raises, raising is better (for both types of opponent)
   - for which $\alpha$ is $s(\theta_h)=r$ and $s(\theta_l)=f$ a symmetric BNE? 
     \vspace*{2cm}
     # high type: $U(r,\theta_h)=\alpha*0+(1-\alpha)*2>\alpha*(-1)+(1-\alpha)*0=U(f,\theta_l)$ => high type plays b.r.; low type: $U(f,\theta_l)=\alpha*(-1)+(1-\alpha)*0=-\alpha$ while $U(r,\theta_l)=\alpha*(-2)+(1-\alpha)*1=1-3\alpha$. Therefore, BNE iff $\alpha\geq 1/2$.
   - what is the symmetric BNE if the above strategy is not?
     # $s(\theta_h)=s(\theta_l)=r$: low type $U(r,\theta_l)=\alpha*(-2)+(1-\alpha)*0$ while $U(f,\theta_l)=-1$; hence BNE if $\alpha\leq 1/2$

* Jury voting
** jury voting I
   players, actions, payoffs:
   - jury with two members ("jurors")
   - jurors simultaneously vote whether to /acquit/ ($a$) or /convict/ ($c$)
   - if both vote $c$, defendant is convicted; otherwise acquitted
   - each juror has payoff
     - 1 if the defendant is either (i) guilty and convicted or (ii) innocent and acquitted
     - 0 otherwise
** jury voting II
   information:
   - before seeing the evidence each juror thinks that the defendant is guilty with probability 0.6
   - each juror $j$ has his own expertise in interpreting the evidence
     - signal $\theta_j\in\{i,g\}$ where $\sigma_i$ "is correct" with probability $0.8$
       - $\theta_j=i$ with probability $0.8$ if the defendant is innocent and with probability $0.2$ if he is guilty
       - $\theta_j=g$ with probability $0.8$ if the defendant is guilty and with probability $0.2$ if he is innocent
     - signal $\theta_j$ is private information of juror $j$
     - signals are assumed to be independent conditional on the defendant's status
** jury voting III
   - let $\mu_j$ be juror $j$'s belief that the defendant is guilty
   - determine $\mu_j$ after $j$ receives signal $g$
     \vspace*{1cm}
     # (0.6*0.8)/(0.6*0.8+0.4*0.2)=6/7
   - determine $\mu_j$ after $j$ receives signal $i$
     \vspace*{1cm}
     # (0.6*0.2)/(0.6*0.2+0.4*0.8)=12/44=3/11
   # - how would a juror vote if he had to decide on his own?
     # acquit if signal i, convict if signal g
   - if juror 1 knew that $\theta_2=g$ and $\theta_1=i$, what would $\mu_j$ be?
     \vspace*{1cm}
     # (0.6*0.8*0.2)/(0.6*0.8*0.2+0.4*0.2*0.8)=0.6
   - is the strategy $s(i)=a$ and $s(g)=c$ a symmetric BNE?
     # No: suppose $\theta_j=i$. juror $j$'s vote matters only if the other juror voted $c$, i.e. if his signal is g; but in this case his belief that the defendant is guilty is greater than 1/2...therefore a is best response!
** jury voting IV: symmetric BNE
   - if $\theta_j=g$, then $\mu_j>1/2$ even if $j$ knew that $\theta_{-j}=i$
     \linebreak $\rightarrow$ $s(g)=c$
   - let each juror vote $c$ with probability $\gamma$ after receiving signal $i$
     - determine the probability that $j$ votes $c$
       \vspace*{0.5cm}
       # 0.6+0.4*\gamma
     - determine the expected payoff of $j$ if $\theta_j=i$ and he votes convict
       \vspace*{1.3cm}
       # pivotal if other votes c; then \mu_j = (0.6*0.2*(0.8+0.2*\gamma)) / (0.6*0.2*(0.8+0.2*\gamma)+0.4*0.8*(0.2+0.8*\gamma))=(0.096+0.024\gamma) / (0.16+0.28\gamma) and payoff of c equals mu_j
     - determine the expected payoff of $j$ if $\theta_j=i$ and he votes acquit
       \vspace*{0.7cm}
       # same mu_j but payoff is now (1-\mu_j)
     - which $\gamma\in[0,1]$ leads to a symmetric BNE?
       \vspace*{0.5cm}
       # indifference condition after receiving signal i: the above calculated mu_j=1/2 which is equivalent to $\gamma=4/29$

* Pricing  with private costs
** Pricing  with private costs 
   - 2 firms set prices, $p_i\in[0,1]$, in order to maximize profits
   - demand of firm $i$ equals $1-p_i+p_j/2$
   - firm $i$ has constant marginal costs $\theta_i\in\{0.3,0.5\}$
   - $\theta_i$ is private information and both types are equally likely
   - find a symmetric BNE
     \vspace*{3cm}
  # symmetric strategy: p^l, p^h;
  # expected profit: 0.5*(p_i-\theta_i)(1-p_i+p^l/2)+0.5*(p_i-\theta_i)(1-p_i+p^h/2)
  # foc: -(p_i-\theta_i)+0.5*(1-p_i+p^l/2)+0.5*(1-p_i+p^h/2)=0
  # b.r.: p_i(\theta_i) = (\theta_i+1+p^l/4+p^h/4) / 2=1/2+\theta_i/2+p^l/8+p^h/8
  # eq. conditions: p^l = 1/2+0.3/2+p^l/8+p^h/8 and p^h = 1/2+0.5/2+p^l/8+p^h/8
  # BNE: p^l=0.88333 p^h=0.98333
